jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/myapp:${{ github.sha }}

      - name: Deploy via SSH (password)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            docker pull ${{ secrets.REGISTRY_URL }}/myapp:${{ github.sha }}
            if (docker ps -a -q --filter "name=myapp") {
              docker stop myapp
              docker rm   myapp
            }
            docker run -d --name myapp --restart always -p 80:80 ${{ secrets.REGISTRY_URL }}/myapp:${{ github.sha }}
